### ISSUE TITLE
Question: what is the license of the source code in this repo?

### ISSUE THREAD

**Issue by jiangzhu-genie** [metodika/node-4d#11]
hi @rlaveaux,

We are interested in using node-4d code in our nodejs application. According to https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository, without a license, the default copyright laws apply. I'd like to confirm do you intend to grant use of the repo under an open source license?

Regards,
Jiang

**Comment by rlaveaux** [comment]
Hi Jian,

Thank you for your message. I have updated the source files with a mention of the MIT license.
I hope this answers your question.

Best,

Rob

**Comment by jiangzhu-genie** [comment]
hi Rob

Thanks a lot for your prompt response, much appreciated

Best Regards,
Jiang
________________________________
